server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "password123"
    sources:
      youtube: false
      soundcloud: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

pluginsDir: "./plugins"
